trigger:
  branches:
    include:
      - trunk
  paths:
    exclude:
      - azure-pipelines.yml
pr:
  branches:
    include:
      - trunk
      - release-v*
      - hotfix-v*
pool:
    vmImage: ubuntu-latest
  
variables:
    phpVersion: 8.2
steps:
- task: UseNode@1
  inputs:
    version: '24.x'
  displayName: 'Install Node.js 24'
- script: npm install -g npm@11.16.0
  displayName: 'Force functinal NPM version'
- task: Npm@1
  inputs:
    command: 'ci'
- task: replacetokens@6
  inputs:
    targetFiles: 'plugin.php'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'ci --omit=dev'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'bc-acalog-wordpress-blocks'
    publishLocation: 'pipeline'
